// react-app/src/components/Navigation.tsx
export const Navigation = () => {
  const navigate = (path: string) => {
    window.history.pushState({}, '', path);
    window.dispatchEvent(new PopStateEvent('popstate'));
  };

  const currentPath = window.location.pathname;

  return (
    <nav style={{ 
      display: 'flex', 
      gap: '1.5rem', 
      alignItems: 'center',
      marginBottom: '2rem',
      padding: '1rem 1.5rem',
      background: 'var(--ra-surface)',
      border: '1px solid var(--ra-border)',
      borderRadius: '8px'
    }}>
      <a 
        className={`ra-link ${currentPath.includes('/products') || currentPath === '/react' ? 'ra-link--active' : ''}`}
        href="/react/products"
        onClick={(e) => {
          e.preventDefault();
          navigate('/react/products');
        }}
      >
        Products
      </a>
      <a 
        className={`ra-link ${currentPath.includes('/about-us') ? 'ra-link--active' : ''}`}
        href="/react/about-us"
        onClick={(e) => {
          e.preventDefault();
          navigate('/react/about-us');
        }}
      >
        About Us
      </a>
    </nav>
  );
};

// vue-app/src/components/Navigation.vue
<script setup lang="ts">
import { computed } from 'vue'

const currentPath = computed(() => window.location.pathname)

function navigate(path: string) {
  window.history.pushState({}, '', path)
  window.dispatchEvent(new PopStateEvent('popstate'))
}
</script>

<template>
  <nav style="display: flex; gap: 1.5rem; align-items: center; margin-bottom: 2rem; padding: 1rem 1.5rem; background: var(--va-surface); border: 1px solid var(--va-border); border-radius: 8px;">
    <a 
      class="va-link" 
      :class="{ 'va-link--active': currentPath.includes('/products') || currentPath === '/vue' }"
      href="/vue/products"
      @click.prevent="navigate('/vue/products')"
    >
      Products
    </a>
    <a 
      class="va-link" 
      :class="{ 'va-link--active': currentPath.includes('/contact-us') }"
      href="/vue/contact-us"
      @click.prevent="navigate('/vue/contact-us')"
    >
      Contact Us
    </a>
  </nav>
</template>

<style scoped>
.va-link {
  color: var(--va-accent);
  text-decoration: underline;
  cursor: pointer;
  transition: color 0.15s ease;
}

.va-link:hover {
  color: var(--va-accent-bright);
  text-decoration: none;
}

.va-link--active {
  font-weight: bold;
  text-decoration: none;
  pointer-events: none;
}
</style>
