// react-app/src/App.tsx
import { useState, useEffect } from 'react';
import './App.css';
import { getGlobalCounter } from './shared-counter';

function App() {
  const [count, setCount] = useState(getGlobalCounter().get());
  
  useEffect(() => {
    const unsubscribe = getGlobalCounter().subscribe((c) => setCount(c));
    return () => unsubscribe();
  }, []);

  const updateCount = (newCount: number) => {
    getGlobalCounter().set(newCount);
  };

  const [messages, setMessages] = useState<string[]>([]);

  const greetings = [
    'Hello from React! 👋',
    'React is alive inside Angular! ⚛',
    'Module Federation 2 works! 🚀',
    'Federated and isolated! 🔒',
    'Cross-framework MFE FTW! 🎉',
  ];

  const handleGreet = () => {
    const msg = greetings[Math.floor(Math.random() * greetings.length)];
    setMessages((prev) => [msg, ...prev].slice(0, 4));
  };

  return (
    <div className="ra-root">
      <div className="ra-header">
        <div className="ra-logo">⚛</div>
        <div>
          <h1 className="ra-title">React Micro-Frontend</h1>
          <p className="ra-subtitle">Loaded via <code>loadRemote('react_app/App')</code></p>
        </div>
      </div>

      <div className="ra-grid">
        {/* Counter card */}
        <div className="ra-card">
          <h2 className="ra-card__title">Isolated State</h2>
          <p className="ra-card__desc">React state is fully isolated in this MFE bundle</p>
          <div className="ra-counter">
            <button
              id="react-decrement"
              className="ra-btn ra-btn--ghost"
              onClick={() => updateCount(count - 1)}
            >
              −
            </button>
            <span className="ra-counter__value">{count}</span>
            <button
              id="react-increment"
              className="ra-btn ra-btn--ghost"
              onClick={() => updateCount(count + 1)}
            >
              +
            </button>
          </div>
          <button
            id="react-reset"
            className="ra-btn ra-btn--sm"
            onClick={() => updateCount(0)}
          >
            Reset
          </button>
        </div>

        {/* Messenger card */}
        <div className="ra-card">
          <h2 className="ra-card__title">Greeting Generator</h2>
          <p className="ra-card__desc">Send a message from inside React</p>
          <button
            id="react-greet"
            className="ra-btn ra-btn--primary"
            onClick={handleGreet}
          >
            Say Hello ✨
          </button>
          <div className="ra-messages">
            {messages.map((m, i) => (
              <div key={i} className="ra-message" style={{ opacity: 1 - i * 0.2 }}>
                {m}
              </div>
            ))}
          </div>
        </div>

        {/* Info card */}
        <div className="ra-card ra-card--info">
          <h2 className="ra-card__title">Remote Info</h2>
          <dl className="ra-dl">
            <dt>Name</dt><dd>react_app</dd>
            <dt>Exposed</dt><dd>./App → mfe-entry.ts</dd>
            <dt>Manifest</dt><dd>http://localhost:3000/mf-manifest.json</dd>
            <dt>Shared</dt><dd>react, react-dom (singleton)</dd>
            <dt>Plugin</dt><dd>@module-federation/vite</dd>
          </dl>
        </div>
      </div>
    </div>
  );
}

export default App;

// vue-app/src/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { getGlobalCounter } from './shared-counter'

const count = ref(getGlobalCounter().get())
let unsubscribe: (() => void) | null = null

onMounted(() => {
  unsubscribe = getGlobalCounter().subscribe(val => {
    count.value = val
  })
})

onUnmounted(() => {
  if (unsubscribe) unsubscribe()
})

const updateCount = (newCount: number) => {
  getGlobalCounter().set(newCount)
}

const todos = ref<string[]>([])
const input = ref('')

function addTodo() {
  if (input.value.trim()) {
    todos.value.push(input.value.trim())
    input.value = ''
  }
}

function removeTodo(i: number) {
  todos.value.splice(i, 1)
}
</script>

<template>
  <div class="va-root">
    <header class="va-header">
      <div class="va-logo">💚</div>
      <div>
        <h1 class="va-title">Vue Micro-Frontend</h1>
        <p class="va-subtitle">Loaded via <code>loadRemote('vue_app/App')</code></p>
      </div>
    </header>

    <div class="va-grid">
      <!-- Counter card -->
      <div class="va-card">
        <h2 class="va-card__title">Reactive Counter</h2>
        <p class="va-card__desc">Vue's reactivity running inside the Angular shell</p>
        <div class="va-counter">
          <button id="vue-decrement" class="va-btn va-btn--ghost" @click="updateCount(count - 1)">−</button>
          <span class="va-counter__value">{{ count }}</span>
          <button id="vue-increment" class="va-btn va-btn--ghost" @click="updateCount(count + 1)">+</button>
        </div>
        <button id="vue-reset" class="va-btn va-btn--sm" @click="updateCount(0)">Reset</button>
      </div>

      <!-- Todo card -->
      <div class="va-card">
        <h2 class="va-card__title">Mini To-Do List</h2>
        <p class="va-card__desc">Stateful Vue list — isolated from the shell</p>
        <div class="va-input-row">
          <input
            id="vue-todo-input"
            v-model="input"
            class="va-input"
            placeholder="Add a task…"
            @keydown.enter="addTodo"
          />
          <button id="vue-todo-add" class="va-btn va-btn--primary" @click="addTodo">Add</button>
        </div>
        <ul class="va-todos">
          <li
            v-for="(todo, i) in todos"
            :key="i"
            class="va-todo"
          >
            <span>{{ todo }}</span>
            <button class="va-todo__remove" @click="removeTodo(i)">✕</button>
          </li>
          <li v-if="todos.length === 0" class="va-todo va-todo--empty">
            No tasks yet
          </li>
        </ul>
      </div>

      <!-- Info card -->
      <div class="va-card va-card--info">
        <h2 class="va-card__title">Remote Info</h2>
        <dl class="va-dl">
          <dt>Name</dt><dd>vue_app</dd>
          <dt>Exposed</dt><dd>./App → mfe-entry.ts</dd>
          <dt>Manifest</dt><dd>http://localhost:3001/mf-manifest.json</dd>
          <dt>Shared</dt><dd>vue (singleton)</dd>
          <dt>Plugin</dt><dd>@module-federation/vite</dd>
        </dl>
      </div>
    </div>
  </div>
</template>

<style scoped>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Inter+Tight:wght@700;800&display=swap');

*,
*::before,
*::after {
  box-sizing: border-box;
}

.va-root {
  background: transparent;
  min-height: 100%;
  padding: 2rem;
  color: var(--color-text);
  font-family: 'Inter', system-ui, sans-serif;
  -webkit-font-smoothing: antialiased;
}

/* Header */
.va-header {
  display: flex;
  align-items: center;
  gap: 1.25rem;
  margin-bottom: 2.5rem;
}

.va-logo {
  font-size: 3rem;
  line-height: 1;
  animation: pulse 2s ease-in-out infinite;
}

@keyframes pulse {
  0%, 100% { filter: drop-shadow(0 0 12px var(--color-vue-glow)); }
  50%       { filter: drop-shadow(0 0 24px var(--color-vue)); }
}

.va-title {
  font-family: 'Inter Tight', sans-serif;
  font-size: 1.75rem;
  font-weight: 800;
  letter-spacing: -0.03em;
  color: var(--color-vue);
  margin-bottom: 0.25rem;
}

.va-subtitle {
  font-size: 0.875rem;
  color: var(--color-text-muted);
}

.va-subtitle code {
  background: var(--color-surface-2);
  border: 1px solid var(--color-border);
  border-radius: 4px;
  padding: 0.1em 0.4em;
  font-size: 0.8125rem;
  color: var(--color-vue);
}

/* Grid */
.va-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
}

@media (max-width: 600px) {
  .va-grid { grid-template-columns: 1fr; }
}

.va-card--info {
  grid-column: 1 / -1;
}

/* Card */
.va-card {
  background: var(--color-surface);
  border: 1px solid var(--color-border);
  border-radius: 10px;
  padding: 1.5rem;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  transition: border-color 0.2s, box-shadow 0.2s;
}

.va-card:hover {
  border-color: var(--color-vue);
  box-shadow: 0 4px 24px var(--color-vue-glow);
}

.va-card__title {
  font-family: 'Inter Tight', sans-serif;
  font-size: 1rem;
  font-weight: 700;
  letter-spacing: -0.02em;
  color: var(--color-text);
}

.va-card__desc {
  font-size: 0.875rem;
  color: var(--color-text-muted);
}

/* Counter */
.va-counter {
  display: flex;
  align-items: center;
  gap: 1.25rem;
  margin: 0.5rem 0;
}

.va-counter__value {
  font-family: 'Inter Tight', sans-serif;
  font-size: 2.5rem;
  font-weight: 800;
  color: var(--color-vue);
  min-width: 3ch;
  text-align: center;
}

/* Buttons */
.va-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0.5rem 1.25rem;
  border-radius: 6px;
  font-size: 0.9375rem;
  font-weight: 500;
  cursor: pointer;
  border: 1px solid transparent;
  transition: all 0.15s ease;
  font-family: inherit;
}

.va-btn--ghost {
  background: var(--color-surface-2);
  color: var(--color-text);
  border-color: var(--color-border);
  width: 2.5rem;
  height: 2.5rem;
  padding: 0;
  font-size: 1.25rem;
}

.va-btn--ghost:hover {
  background: var(--color-vue-glow);
  border-color: var(--color-vue);
  color: var(--color-vue);
}

.va-btn--sm {
  background: var(--color-surface-2);
  color: var(--color-text-muted);
  border-color: var(--color-border);
  font-size: 0.8125rem;
  padding: 0.375rem 0.875rem;
  align-self: flex-start;
}

.va-btn--primary {
  background: var(--color-vue-glow);
  color: var(--color-vue);
  border-color: var(--color-vue);
}

.va-btn--primary:hover {
  background: var(--color-vue-glow);
  box-shadow: 0 0 12px var(--color-vue-glow);
}

/* Input */
.va-input-row {
  display: flex;
  gap: 0.5rem;
}

.va-input {
  flex: 1;
  background: var(--color-surface-2);
  border: 1px solid var(--color-border);
  border-radius: 6px;
  padding: 0.5rem 0.875rem;
  color: var(--color-text);
  font-size: 0.9375rem;
  font-family: inherit;
  outline: none;
  transition: border-color 0.15s;
}

.va-input:focus {
  border-color: var(--color-vue);
}

.va-input::placeholder {
  color: var(--color-text-muted);
}

/* Todos */
.va-todos {
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
}

.va-todo {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: var(--color-surface-2);
  border: 1px solid var(--color-border);
  border-radius: 6px;
  padding: 0.5rem 0.875rem;
  font-size: 0.875rem;
}

.va-todo--empty {
  color: var(--color-text-muted);
  justify-content: center;
}

.va-todo__remove {
  background: none;
  border: none;
  color: var(--color-text-muted);
  cursor: pointer;
  font-size: 0.75rem;
  padding: 0.125rem 0.25rem;
  border-radius: 4px;
  transition: color 0.15s, background 0.15s;
}

.va-todo__remove:hover {
  color: var(--color-angular);
  background: var(--color-angular-glow);
}

/* DL info table */
.va-dl {
  display: grid;
  grid-template-columns: auto 1fr;
  gap: 0.5rem 1.5rem;
  font-size: 0.875rem;
}

.va-dl dt {
  color: var(--color-text-muted);
  font-weight: 500;
}

.va-dl dd {
  color: var(--color-text);
  font-family: 'JetBrains Mono', 'Fira Code', monospace;
  font-size: 0.8125rem;
  word-break: break-all;
}
</style>
